modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="explosivearrows"
version="0.1.0"
displayName="Explosive Arrows Mod"
logoFile="explosivearrows.png"
credits="WifftLord"
authors="Wifft"
description='''
Mod that add explosive arrows to the game.
'''
[[dependencies.explosivearrows]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.explosivearrows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
